const model = (id, label, repo, configuration, template, summary, caption, extra = {}) => ({
  id,
  label,
  repo,
  configuration,
  template,
  summary,
  caption,
  ...extra,
});

const family = (
  id,
  label,
  vocabStatus,
  vocabBadge,
  vocabSummary,
  vocabCaption,
  models,
  extra = {},
) => ({
  id,
  label,
  vocabStatus,
  vocabBadge,
  vocabSummary,
  vocabCaption,
  models,
  ...extra,
});

export const LINE_CATALOG = [
  {
    id: 'qwen',
    label: 'Qwen',
    lineSummary: 'Qwen 2.5, Qwen 3, and Qwen 3.5 are grouped here as successive generations of one Chinese model line. In this browser build each of those text families now carries its full public size ladder, and each ladder reuses one exact tokenizer bundle across all listed checkpoints.',
    lineCaption: 'This line groups the full public text families for Qwen 2.5, Qwen 3, and Qwen 3.5 before you pick a concrete size.',
    families: [
      family(
        'qwen35',
        'Qwen 3.5',
        'exact',
        'Exact shared vocabulary',
        'All listed Qwen 3.5 checkpoints resolve to the same public tokenizer.json, so changing model size does not change vocabulary or token IDs anywhere in the Qwen 3.5 ladder.',
        'All listed Qwen 3.5 configurations point to the same tokenizer.json.',
        [
          model(
            'qwen3.5-0.8b',
            'Qwen3.5-0.8B',
            'Qwen/Qwen3.5-0.8B',
            '0.8B',
            'Qwen 3.5 instruct',
            'Smallest public Qwen 3.5 checkpoint, useful for inspecting the exact Qwen 3.5 vocabulary at the lightest scale.',
            'Public Qwen 3.5 tokenizer files for the 0.8B checkpoint.',
          ),
          model(
            'qwen3.5-2b',
            'Qwen3.5-2B',
            'Qwen/Qwen3.5-2B',
            '2B',
            'Qwen 3.5 instruct',
            'Compact Qwen 3.5 checkpoint that keeps the exact same tokenizer surface as the rest of the Qwen 3.5 family.',
            'Public Qwen 3.5 tokenizer files for the 2B checkpoint.',
          ),
          model(
            'qwen3.5-4b',
            'Qwen3.5-4B',
            'Qwen/Qwen3.5-4B',
            '4B',
            'Qwen 3.5 instruct',
            'The original anchor for this page, now placed inside the full Qwen 3.5 family ladder.',
            'Public Qwen 3.5 tokenizer files for the 4B checkpoint.',
          ),
          model(
            'qwen3.5-9b',
            'Qwen3.5-9B',
            'Qwen/Qwen3.5-9B',
            '9B',
            'Qwen 3.5 instruct',
            'Mid-sized dense Qwen 3.5 checkpoint that still reuses the exact same tokenizer bundle as the smaller releases.',
            'Public Qwen 3.5 tokenizer files for the 9B checkpoint.',
          ),
          model(
            'qwen3.5-27b',
            'Qwen3.5-27B',
            'Qwen/Qwen3.5-27B',
            '27B',
            'Qwen 3.5 instruct',
            'Larger dense Qwen 3.5 checkpoint with identical token IDs to the rest of the listed Qwen 3.5 family.',
            'Public Qwen 3.5 tokenizer files for the 27B checkpoint.',
          ),
          model(
            'qwen3.5-35b-a3b',
            'Qwen3.5-35B-A3B',
            'Qwen/Qwen3.5-35B-A3B',
            '35B A3B',
            'Qwen 3.5 instruct',
            'Sparse MoE Qwen 3.5 checkpoint that still keeps the exact shared Qwen 3.5 tokenizer surface.',
            'Public Qwen 3.5 tokenizer files for the 35B A3B checkpoint.',
          ),
          model(
            'qwen3.5-122b-a10b',
            'Qwen3.5-122B-A10B',
            'Qwen/Qwen3.5-122B-A10B',
            '122B A10B',
            'Qwen 3.5 instruct',
            'Larger sparse Qwen 3.5 checkpoint with the same token boundaries as the rest of the public Qwen 3.5 ladder.',
            'Public Qwen 3.5 tokenizer files for the 122B A10B checkpoint.',
          ),
          model(
            'qwen3.5-397b-a17b',
            'Qwen3.5-397B-A17B',
            'Qwen/Qwen3.5-397B-A17B',
            '397B A17B',
            'Qwen 3.5 instruct',
            'Largest public Qwen 3.5 checkpoint in the family, still anchored to the exact same tokenizer bundle as the smaller sizes.',
            'Public Qwen 3.5 tokenizer files for the 397B A17B checkpoint.',
          ),
        ],
        {
          tokenizerSource: 'Qwen/Qwen3.5-0.8B',
          tokenizerCacheKey: 'qwen35',
          tokenizerSourceLabel: 'shared tokenizer assets from Qwen/Qwen3.5-0.8B',
        },
      ),
      family(
        'qwen3',
        'Qwen 3',
        'exact',
        'Exact shared vocabulary',
        'All listed Qwen 3 checkpoints resolve to the same public tokenizer.json, so changing size or switching into the sparse A3B variant does not change the vocabulary or token IDs.',
        'All listed Qwen 3 configurations point to the same tokenizer.json.',
        [
          model(
            'qwen3-0.6b',
            'Qwen3-0.6B',
            'Qwen/Qwen3-0.6B',
            '0.6B',
            'Qwen 3 instruct',
            'Smallest public Qwen 3 checkpoint in the catalog, useful for seeing the shared Qwen 3 vocabulary at the lightest scale.',
            'Public Qwen 3 tokenizer files for the 0.6B checkpoint.',
          ),
          model(
            'qwen3-1.7b',
            'Qwen3-1.7B',
            'Qwen/Qwen3-1.7B',
            '1.7B',
            'Qwen 3 instruct',
            'Second Qwen 3 checkpoint in the dense ladder, still reusing the exact shared Qwen 3 tokenizer surface.',
            'Public Qwen 3 tokenizer files for the 1.7B checkpoint.',
          ),
          model(
            'qwen3-4b',
            'Qwen3-4B',
            'Qwen/Qwen3-4B',
            '4B',
            'Qwen 3 instruct',
            'Mid-sized Qwen 3 checkpoint that keeps the same tokenizer surface as the other listed Qwen 3 sizes.',
            'Public Qwen 3 tokenizer files for the 4B checkpoint.',
          ),
          model(
            'qwen3-8b',
            'Qwen3-8B',
            'Qwen/Qwen3-8B',
            '8B',
            'Qwen 3 instruct',
            'Widely used Qwen 3 checkpoint that still shares token IDs with the rest of the Qwen 3 family.',
            'Public Qwen 3 tokenizer files for the 8B checkpoint.',
          ),
          model(
            'qwen3-14b',
            'Qwen3-14B',
            'Qwen/Qwen3-14B',
            '14B',
            'Qwen 3 instruct',
            'Larger dense Qwen 3 checkpoint that keeps the same tokenizer surface as the smaller family members.',
            'Public Qwen 3 tokenizer files for the 14B checkpoint.',
          ),
          model(
            'qwen3-30b-a3b',
            'Qwen3-30B-A3B',
            'Qwen/Qwen3-30B-A3B',
            '30B A3B',
            'Qwen 3 instruct',
            'Sparse MoE Qwen 3 checkpoint that still resolves to the exact shared Qwen 3 tokenizer bundle.',
            'Public Qwen 3 tokenizer files for the 30B A3B checkpoint.',
          ),
          model(
            'qwen3-32b',
            'Qwen3-32B',
            'Qwen/Qwen3-32B',
            '32B',
            'Qwen 3 instruct',
            'Largest dense Qwen 3 checkpoint in the public ladder, still aligned to the same vocabulary as the smaller releases.',
            'Public Qwen 3 tokenizer files for the 32B checkpoint.',
          ),
        ],
        {
          tokenizerSource: 'Qwen/Qwen3-0.6B',
          tokenizerCacheKey: 'qwen3',
          tokenizerSourceLabel: 'shared tokenizer assets from Qwen/Qwen3-0.6B',
        },
      ),
      family(
        'qwen25',
        'Qwen 2.5',
        'exact',
        'Exact shared vocabulary',
        'All listed Qwen 2.5 instruct checkpoints resolve to the same public tokenizer.json, so token IDs stay aligned across the full public dense ladder from 0.5B through 72B.',
        'All listed Qwen 2.5 configurations point to the same tokenizer.json.',
        [
          model(
            'qwen2.5-0.5b-instruct',
            'Qwen2.5-0.5B-Instruct',
            'Qwen/Qwen2.5-0.5B-Instruct',
            '0.5B Instruct',
            'Qwen 2.5 instruct',
            'Smallest public Qwen 2.5 instruct checkpoint, useful for inspecting the shared Qwen 2.5 vocabulary at tiny scale.',
            'Public Qwen 2.5 instruct tokenizer files for the 0.5B model.',
          ),
          model(
            'qwen2.5-1.5b-instruct',
            'Qwen2.5-1.5B-Instruct',
            'Qwen/Qwen2.5-1.5B-Instruct',
            '1.5B Instruct',
            'Qwen 2.5 instruct',
            'Compact Qwen 2.5 instruct checkpoint with the same vocabulary as the larger listed Qwen 2.5 models.',
            'Public Qwen 2.5 instruct tokenizer files for the 1.5B model.',
          ),
          model(
            'qwen2.5-3b-instruct',
            'Qwen2.5-3B-Instruct',
            'Qwen/Qwen2.5-3B-Instruct',
            '3B Instruct',
            'Qwen 2.5 instruct',
            'Smaller mid-range Qwen 2.5 instruct checkpoint that keeps the same tokenizer surface as the rest of the family.',
            'Public Qwen 2.5 instruct tokenizer files for the 3B model.',
          ),
          model(
            'qwen2.5-7b-instruct',
            'Qwen2.5-7B-Instruct',
            'Qwen/Qwen2.5-7B-Instruct',
            '7B Instruct',
            'Qwen 2.5 instruct',
            'A widely used Qwen 2.5 instruct checkpoint that keeps token IDs aligned with the smaller and larger Qwen 2.5 sizes.',
            'Public Qwen 2.5 instruct tokenizer files for the 7B model.',
          ),
          model(
            'qwen2.5-14b-instruct',
            'Qwen2.5-14B-Instruct',
            'Qwen/Qwen2.5-14B-Instruct',
            '14B Instruct',
            'Qwen 2.5 instruct',
            'Larger Qwen 2.5 instruct checkpoint that still uses the same tokenizer surface as the smaller listed variants.',
            'Public Qwen 2.5 instruct tokenizer files for the 14B model.',
          ),
          model(
            'qwen2.5-32b-instruct',
            'Qwen2.5-32B-Instruct',
            'Qwen/Qwen2.5-32B-Instruct',
            '32B Instruct',
            'Qwen 2.5 instruct',
            'Large Qwen 2.5 instruct checkpoint that still reuses the exact shared Qwen 2.5 tokenizer bundle.',
            'Public Qwen 2.5 instruct tokenizer files for the 32B model.',
          ),
          model(
            'qwen2.5-72b-instruct',
            'Qwen2.5-72B-Instruct',
            'Qwen/Qwen2.5-72B-Instruct',
            '72B Instruct',
            'Qwen 2.5 instruct',
            'Largest public Qwen 2.5 instruct checkpoint in the browser-friendly family ladder, still sharing token IDs with every smaller size.',
            'Public Qwen 2.5 instruct tokenizer files for the 72B model.',
          ),
        ],
        {
          tokenizerSource: 'Qwen/Qwen2.5-0.5B-Instruct',
          tokenizerCacheKey: 'qwen25',
          tokenizerSourceLabel: 'shared tokenizer assets from Qwen/Qwen2.5-0.5B-Instruct',
        },
      ),
    ],
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    lineSummary: 'The public DeepSeek reasoning slice now covers both Qwen-based and Llama-based R1 distill families. Each family keeps one exact tokenizer bundle across its listed checkpoints, so the interesting differences are prompt serialization and family lineage rather than size-specific vocabulary drift.',
    lineCaption: 'DeepSeek now contributes two browser-loadable R1 distill families: one Qwen-based and one Llama-based.',
    families: [
      family(
        'deepseek-r1-qwen',
        'R1 Distill (Qwen)',
        'exact',
        'Exact shared vocabulary',
        'The listed DeepSeek R1 Distill Qwen checkpoints share the same public tokenizer.json, so vocabulary stays aligned all the way from 1.5B through 32B.',
        'All listed DeepSeek R1 Distill Qwen configurations point to the same tokenizer.json.',
        [
          model(
            'deepseek-r1-distill-qwen-1.5b',
            'DeepSeek-R1-Distill-Qwen-1.5B',
            'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B',
            '1.5B',
            'DeepSeek reasoning',
            'The smallest public Qwen-sized R1 distill checkpoint, useful for comparing DeepSeek prompt serialization without changing the shared vocabulary.',
            'Public DeepSeek R1 Distill Qwen tokenizer files for the 1.5B release.',
          ),
          model(
            'deepseek-r1-distill-qwen-7b',
            'DeepSeek-R1-Distill-Qwen-7B',
            'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
            '7B',
            'DeepSeek reasoning',
            'The 7B R1 distill checkpoint keeps the same tokenizer surface as the smaller and larger Qwen-based DeepSeek distills.',
            'Public DeepSeek R1 Distill Qwen tokenizer files for the 7B release.',
          ),
          model(
            'deepseek-r1-distill-qwen-14b',
            'DeepSeek-R1-Distill-Qwen-14B',
            'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B',
            '14B',
            'DeepSeek reasoning',
            'Larger Qwen-based R1 distill checkpoint that still resolves to the exact shared DeepSeek Qwen tokenizer bundle.',
            'Public DeepSeek R1 Distill Qwen tokenizer files for the 14B release.',
          ),
          model(
            'deepseek-r1-distill-qwen-32b',
            'DeepSeek-R1-Distill-Qwen-32B',
            'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
            '32B',
            'DeepSeek reasoning',
            'Largest public Qwen-based R1 distill checkpoint, still aligned to the same tokenizer.json as the rest of the family.',
            'Public DeepSeek R1 Distill Qwen tokenizer files for the 32B release.',
          ),
        ],
        {
          tokenizerSource: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B',
          tokenizerCacheKey: 'deepseek-r1-qwen',
          tokenizerSourceLabel: 'shared tokenizer assets from deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B',
        },
      ),
      family(
        'deepseek-r1-llama',
        'R1 Distill (Llama)',
        'exact',
        'Exact shared vocabulary',
        'The listed DeepSeek R1 Distill Llama checkpoints resolve to the same public tokenizer.json, so token IDs stay aligned between the 8B and 70B Llama-based distills.',
        'All listed DeepSeek R1 Distill Llama configurations point to the same tokenizer.json.',
        [
          model(
            'deepseek-r1-distill-llama-8b',
            'DeepSeek-R1-Distill-Llama-8B',
            'deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
            '8B',
            'DeepSeek reasoning',
            'Smaller Llama-based R1 distill checkpoint, useful for contrasting the Llama tokenizer lineage against the Qwen-based distills.',
            'Public DeepSeek R1 Distill Llama tokenizer files for the 8B release.',
          ),
          model(
            'deepseek-r1-distill-llama-70b',
            'DeepSeek-R1-Distill-Llama-70B',
            'deepseek-ai/DeepSeek-R1-Distill-Llama-70B',
            '70B',
            'DeepSeek reasoning',
            'Largest public Llama-based R1 distill checkpoint, still sharing the exact same tokenizer surface as the 8B sibling.',
            'Public DeepSeek R1 Distill Llama tokenizer files for the 70B release.',
          ),
        ],
        {
          tokenizerSource: 'deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
          tokenizerCacheKey: 'deepseek-r1-llama',
          tokenizerSourceLabel: 'shared tokenizer assets from deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
        },
      ),
    ],
  },
  {
    id: 'kimi',
    label: 'Kimi',
    lineSummary: 'Kimi now has first-class support in the browser build. The K2 and Kimi Linear text families load from a local tokenizer bundle converted from MoonshotAI public tiktoken assets, K2.5 uses a newer converted bundle, and Kimi Dev rides its own browser-ready tokenizer.json.',
    lineCaption: 'The Kimi line now covers MoonshotAI public text checkpoints instead of only showing an unsupported placeholder.',
    families: [
      family(
        'kimi-k2',
        'Kimi K2',
        'exact',
        'Exact shared vocabulary',
        'Kimi K2 Base, Instruct, and Thinking all publish the same tiktoken vocabulary, so the token IDs stay aligned while the chat templates diverge by release.',
        'These Kimi K2 releases share one exact tiktoken vocabulary while keeping different chat templates.',
        [
          model(
            'kimi-k2-base',
            'Kimi-K2-Base',
            'moonshotai/Kimi-K2-Base',
            'K2 Base',
            'Kimi K2 base template',
            'Base Kimi K2 checkpoint with the shared K2 tokenizer surface and a simpler default chat template.',
            'Public Kimi K2 tokenizer assets for the base release, converted into a browser bundle.',
            { chatTemplatePath: './assets/chat-templates/kimi-k2-base.jinja' },
          ),
          model(
            'kimi-k2-instruct',
            'Kimi-K2-Instruct',
            'moonshotai/Kimi-K2-Instruct',
            'K2 Instruct',
            'Kimi K2 instruct template',
            'Instruction-tuned Kimi K2 checkpoint with the same shared K2 vocabulary but a richer tool-aware chat template.',
            'Public Kimi K2 tokenizer assets for the instruct release, converted into a browser bundle.',
            { chatTemplatePath: './assets/chat-templates/kimi-k2-instruct.jinja' },
          ),
          model(
            'kimi-k2-thinking',
            'Kimi-K2-Thinking',
            'moonshotai/Kimi-K2-Thinking',
            'K2 Thinking',
            'Kimi K2 thinking template',
            'Reasoning-tuned Kimi K2 checkpoint that keeps the same exact K2 tokenizer while exposing explicit `<think>` serialization in chat mode.',
            'Public Kimi K2 tokenizer assets for the thinking release, converted into a browser bundle.',
            { chatTemplatePath: './assets/chat-templates/kimi-k2-thinking.jinja' },
          ),
        ],
        {
          tokenizerSource: './assets/kimi-k2',
          tokenizerCacheKey: 'kimi-k2',
          tokenizerSourceLabel: 'a local browser bundle converted from MoonshotAI Kimi K2 public tiktoken assets',
        },
      ),
      family(
        'kimi-linear',
        'Kimi Linear 48B A3B',
        'exact',
        'Exact shared vocabulary',
        'Kimi Linear Base and Instruct reuse the same public Kimi tiktoken vocabulary as the K2 family, so token IDs stay aligned even though the model line and chat template shift.',
        'These Kimi Linear releases share one exact tiktoken vocabulary.',
        [
          model(
            'kimi-linear-48b-a3b-base',
            'Kimi-Linear-48B-A3B-Base',
            'moonshotai/Kimi-Linear-48B-A3B-Base',
            '48B A3B Base',
            'Kimi Linear template',
            'Base Kimi Linear checkpoint that keeps the exact shared Kimi tokenizer while shifting to the Linear model line.',
            'Public Kimi Linear tokenizer assets for the base release, converted into a browser bundle.',
            { chatTemplatePath: './assets/chat-templates/kimi-linear.jinja' },
          ),
          model(
            'kimi-linear-48b-a3b-instruct',
            'Kimi-Linear-48B-A3B-Instruct',
            'moonshotai/Kimi-Linear-48B-A3B-Instruct',
            '48B A3B Instruct',
            'Kimi Linear template',
            'Instruction-tuned Kimi Linear checkpoint that keeps the exact shared Kimi tokenizer surface.',
            'Public Kimi Linear tokenizer assets for the instruct release, converted into a browser bundle.',
            { chatTemplatePath: './assets/chat-templates/kimi-linear.jinja' },
          ),
        ],
        {
          tokenizerSource: './assets/kimi-k2',
          tokenizerCacheKey: 'kimi-k2',
          tokenizerSourceLabel: 'a local browser bundle converted from MoonshotAI Kimi K2 public tiktoken assets',
        },
      ),
      family(
        'kimi-k25',
        'Kimi K2.5',
        'single',
        'Single public configuration',
        'Kimi K2.5 currently contributes one public browser-converted text checkpoint here, so there is no sibling tokenizer comparison inside this family yet.',
        'Kimi K2.5 is represented by a single public configuration in this browser build.',
        [
          model(
            'kimi-k25',
            'Kimi-K2.5',
            'moonshotai/Kimi-K2.5',
            'K2.5',
            'Kimi K2.5 reasoning template',
            'Newest public Kimi text checkpoint in the catalog, using its own converted tiktoken bundle and a tool-aware reasoning template.',
            'Public Kimi K2.5 tokenizer assets converted into a browser bundle.',
            { chatTemplatePath: './assets/chat-templates/kimi-k25.jinja' },
          ),
        ],
        {
          tokenizerSource: './assets/kimi-k25',
          tokenizerCacheKey: 'kimi-k25',
          tokenizerSourceLabel: 'a local browser bundle converted from MoonshotAI Kimi K2.5 public tiktoken assets',
        },
      ),
      family(
        'kimi-dev',
        'Kimi Dev',
        'single',
        'Single public configuration',
        'Kimi Dev currently contributes one browser-ready public configuration here, using a separate Qwen-style tokenizer surface instead of the K2 tiktoken bundle.',
        'Kimi Dev is represented by a single public configuration in this browser build.',
        [
          model(
            'kimi-dev-72b',
            'Kimi-Dev-72B',
            'moonshotai/Kimi-Dev-72B',
            '72B',
            'Kimi Dev chat',
            'Developer-tuned Moonshot release that ships a browser-ready tokenizer.json directly from the upstream repo.',
            'Public Kimi Dev tokenizer files and chat template.',
          ),
        ],
      ),
    ],
  },
  {
    id: 'minimax',
    label: 'MiniMax',
    lineSummary: 'MiniMax is split into separate public tokenizer families here: the M1 line shares one exact tokenizer across the 40k and 80k configs, while Text-01 is a separate tokenizer surface with its own chat template.',
    lineCaption: 'MiniMax separates its M1 and Text-01 tokenizer families before you pick a configuration.',
    families: [
      family(
        'minimax-m1',
        'MiniMax M1',
        'exact',
        'Exact shared vocabulary',
        'MiniMax M1 40k and 80k resolve to the same public tokenizer.json, so changing the context-window configuration does not change token IDs.',
        'All listed MiniMax M1 configurations point to the same tokenizer.json.',
        [
          model(
            'minimax-m1-40k',
            'MiniMax-M1-40k',
            'MiniMaxAI/MiniMax-M1-40k',
            'M1 40k',
            'MiniMax M1 chat',
            'The shorter-context MiniMax M1 release, useful for inspecting the shared MiniMax M1 vocabulary without changing tokenizer IDs.',
            'Public MiniMax M1 tokenizer files for the 40k release.',
            { chatContentFormat: 'array-text' },
          ),
          model(
            'minimax-m1-80k',
            'MiniMax-M1-80k',
            'MiniMaxAI/MiniMax-M1-80k',
            'M1 80k',
            'MiniMax M1 chat',
            'Longer-context MiniMax M1 release that keeps the same tokenizer surface as the 40k checkpoint.',
            'Public MiniMax M1 tokenizer files for the 80k release.',
            { chatContentFormat: 'array-text' },
          ),
        ],
        {
          tokenizerSource: 'MiniMaxAI/MiniMax-M1-40k',
          tokenizerCacheKey: 'minimax-m1',
          tokenizerSourceLabel: 'shared tokenizer assets from MiniMaxAI/MiniMax-M1-40k',
        },
      ),
      family(
        'minimax-text-01',
        'MiniMax Text 01',
        'single',
        'Single public configuration',
        'MiniMax Text 01 is represented by one browser-fetchable public configuration here, so there is no sibling tokenizer comparison inside this family yet.',
        'MiniMax Text 01 is represented by a single public configuration in this static build.',
        [
          model(
            'minimax-text-01',
            'MiniMax-Text-01',
            'MiniMaxAI/MiniMax-Text-01',
            'Text 01',
            'MiniMax Text 01 chat',
            'MiniMax Text 01 uses its own prompt serialization and tokenizer surface alongside the M1 family.',
            'Public MiniMax Text 01 tokenizer files and chat template.',
            { chatContentFormat: 'array-text' },
          ),
        ],
      ),
    ],
  },
  {
    id: 'yi',
    label: 'Yi',
    lineSummary: 'Yi 1.5 is another Chinese open-source line that keeps the same base SentencePiece vocabulary across the listed chat checkpoints, even though the browser-facing tokenizer.json wrappers are not all identical.',
    lineCaption: 'Yi currently contributes one shared-base family here.',
    families: [
      family(
        'yi-1.5',
        'Yi 1.5',
        'base',
        'Shared base vocabulary',
        'All listed Yi 1.5 checkpoints share the same tokenizer.model. The 6B and 34B tokenizer.json files match exactly, while the 9B wrapper differs, so the base SentencePiece vocabulary is shared even though the browser-facing tokenizer bundles are not all identical.',
        'The base SentencePiece vocabulary is shared across Yi 1.5, while tokenizer.json wrappers are not all identical.',
        [
          model(
            'yi-1.5-6b-chat',
            'Yi-1.5-6B-Chat',
            '01-ai/Yi-1.5-6B-Chat',
            '6B Chat',
            'Yi chat',
            'Smaller Yi 1.5 chat checkpoint with the shared Yi SentencePiece base vocabulary.',
            'Public Yi 1.5 tokenizer files for the 6B chat release.',
          ),
          model(
            'yi-1.5-9b-chat',
            'Yi-1.5-9B-Chat',
            '01-ai/Yi-1.5-9B-Chat',
            '9B Chat',
            'Yi chat',
            'Mid-sized Yi 1.5 chat checkpoint that keeps the same base tokenizer model even though the tokenizer.json wrapper differs from the 6B and 34B releases.',
            'Public Yi 1.5 tokenizer files for the 9B chat release.',
          ),
          model(
            'yi-1.5-34b-chat',
            'Yi-1.5-34B-Chat',
            '01-ai/Yi-1.5-34B-Chat',
            '34B Chat',
            'Yi chat',
            'Largest listed Yi 1.5 chat checkpoint, still anchored to the same base SentencePiece vocabulary as the smaller Yi releases.',
            'Public Yi 1.5 tokenizer files for the 34B chat release.',
          ),
        ],
      ),
    ],
  },
  {
    id: 'mistral',
    label: 'Mistral',
    lineSummary: 'The public Mistral ecosystem is kept in one family bucket here because the interesting tokenizer comparison is across Mistral, Mixtral, Ministral, and Mistral Small releases that ship different tokenizer files.',
    lineCaption: 'One Mistral ecosystem family is exposed here, with tokenizer differences shown across its configurations.',
    families: [
      family(
        'mistral',
        'Mistral ecosystem',
        'mixed',
        'Different tokenizer files',
        'The listed Mistral-family checkpoints stay in one ecosystem, but their public tokenizer files are not identical, so token boundaries can diverge meaningfully across configurations.',
        'These Mistral-family configurations ship different public tokenizer files.',
        [
          model(
            'mistral-7b-instruct-v0.3',
            'Mistral-7B-Instruct-v0.3',
            'mistralai/Mistral-7B-Instruct-v0.3',
            '7B Instruct v0.3',
            'Mistral instruct',
            'Canonical Mistral instruct checkpoint in the public browser-friendly lineup.',
            'Public Mistral tokenizer files for the v0.3 instruct release.',
          ),
          model(
            'mistral-nemo-instruct-2407',
            'Mistral-Nemo-Instruct-2407',
            'mistralai/Mistral-Nemo-Instruct-2407',
            'Nemo 12B Instruct',
            'Mistral Nemo instruct',
            'Long-context Mistral Nemo release with its own tokenizer surface inside the broader Mistral ecosystem.',
            'Public Mistral Nemo tokenizer files for the instruct release.',
          ),
          model(
            'mixtral-8x7b-instruct-v0.1',
            'Mixtral-8x7B-Instruct-v0.1',
            'mistralai/Mixtral-8x7B-Instruct-v0.1',
            '8x7B Instruct v0.1',
            'Mixtral instruct',
            'Sparse MoE checkpoint in the Mistral family, useful for comparing a separate tokenizer surface within the same ecosystem.',
            'Public Mixtral tokenizer files for the instruct release.',
          ),
          model(
            'mixtral-8x22b-instruct-v0.1',
            'Mixtral-8x22B-Instruct-v0.1',
            'mistralai/Mixtral-8x22B-Instruct-v0.1',
            '8x22B Instruct v0.1',
            'Mixtral instruct',
            'Larger Mixtral release with its own tokenizer surface inside the broader Mistral family.',
            'Public Mixtral tokenizer files for the 8x22B instruct release.',
          ),
          model(
            'mistral-small-24b-instruct-2501',
            'Mistral-Small-24B-Instruct-2501',
            'mistralai/Mistral-Small-24B-Instruct-2501',
            'Small 24B Instruct 2501',
            'Mistral Small instruct',
            'Smaller dense Mistral release with its own tokenizer surface in the public repos.',
            'Public Mistral Small tokenizer files for the 24B instruct release.',
          ),
          model(
            'ministral-8b-instruct-2410',
            'Ministral-8B-Instruct-2410',
            'mistralai/Ministral-8B-Instruct-2410',
            '8B Instruct 2410',
            'Ministral instruct',
            'Earlier compact Ministral release with its own tokenizer surface in the public repos.',
            'Public Ministral tokenizer files for the 8B instruct release.',
          ),
          model(
            'ministral-3-3b-instruct-2512',
            'Ministral-3-3B-Instruct-2512',
            'mistralai/Ministral-3-3B-Instruct-2512',
            '3B Instruct 2512',
            'Ministral 3 instruct',
            'Smallest public Ministral 3 release, useful for comparing the refreshed Ministral tokenizer surface against older siblings.',
            'Public Ministral 3 tokenizer files for the 3B instruct release.',
          ),
          model(
            'ministral-3-8b-instruct-2512',
            'Ministral-3-8B-Instruct-2512',
            'mistralai/Ministral-3-8B-Instruct-2512',
            '8B Instruct 2512',
            'Ministral 3 instruct',
            'Mid-sized Ministral 3 checkpoint with the refreshed Ministral 3 tokenizer surface.',
            'Public Ministral 3 tokenizer files for the 8B instruct release.',
          ),
          model(
            'ministral-3-14b-instruct-2512',
            'Ministral-3-14B-Instruct-2512',
            'mistralai/Ministral-3-14B-Instruct-2512',
            '14B Instruct 2512',
            'Ministral 3 instruct',
            'Largest public Ministral 3 release, still carrying its own tokenizer surface inside the Mistral ecosystem.',
            'Public Ministral 3 tokenizer files for the 14B instruct release.',
          ),
        ],
      ),
    ],
  },
  {
    id: 'phi',
    label: 'Phi',
    lineSummary: 'Phi 3 and Phi 3.5 stay in one family here because the base SentencePiece vocabulary persists across the listed checkpoints even when tokenizer.json wrappers differ.',
    lineCaption: 'Phi stays as one shared-base family in this browser build.',
    families: [
      family(
        'phi',
        'Phi 3 / 3.5',
        'base',
        'Shared base vocabulary',
        'These Phi configs reuse the same public tokenizer.model but ship different tokenizer.json wrappers. The base SentencePiece vocabulary matches even though per-config metadata can differ.',
        'The base SentencePiece vocabulary is shared, while tokenizer.json wrappers differ by configuration.',
        [
          model(
            'phi-3-mini-4k-instruct',
            'Phi-3-mini-4k-instruct',
            'microsoft/Phi-3-mini-4k-instruct',
            '3 Mini 4k',
            'Phi instruct',
            'Compact Phi 3 instruct checkpoint with the shared Phi SentencePiece base vocabulary.',
            'Public Phi tokenizer files for the 3 Mini 4k instruct release.',
          ),
          model(
            'phi-3-mini-128k-instruct',
            'Phi-3-mini-128k-instruct',
            'microsoft/Phi-3-mini-128k-instruct',
            '3 Mini 128k',
            'Phi instruct',
            'Long-context Phi 3 mini release that keeps the same tokenizer wrapper as the 4k mini checkpoint.',
            'Public Phi tokenizer files for the 3 Mini 128k instruct release.',
          ),
          model(
            'phi-3-medium-4k-instruct',
            'Phi-3-medium-4k-instruct',
            'microsoft/Phi-3-medium-4k-instruct',
            '3 Medium 4k',
            'Phi instruct',
            'Mid-sized Phi 3 instruct checkpoint that keeps the same base SentencePiece vocabulary as the other listed Phi releases.',
            'Public Phi tokenizer files for the 3 Medium 4k instruct release.',
          ),
          model(
            'phi-3-medium-128k-instruct',
            'Phi-3-medium-128k-instruct',
            'microsoft/Phi-3-medium-128k-instruct',
            '3 Medium 128k',
            'Phi instruct',
            'Long-context Phi 3 medium release that keeps the same tokenizer wrapper as the 4k medium checkpoint.',
            'Public Phi tokenizer files for the 3 Medium 128k instruct release.',
          ),
          model(
            'phi-3.5-mini-instruct',
            'Phi-3.5-mini-instruct',
            'microsoft/Phi-3.5-mini-instruct',
            '3.5 Mini',
            'Phi instruct',
            'Newer Phi 3.5 instruct checkpoint that still reuses the same base tokenizer model as the listed Phi 3 variants.',
            'Public Phi tokenizer files for the 3.5 Mini instruct release.',
          ),
          model(
            'phi-3.5-moe-instruct',
            'Phi-3.5-MoE-instruct',
            'microsoft/Phi-3.5-MoE-instruct',
            '3.5 MoE',
            'Phi instruct',
            'Sparse Phi 3.5 MoE checkpoint that still shares the same SentencePiece base vocabulary as the rest of the Phi family.',
            'Public Phi tokenizer files for the 3.5 MoE instruct release.',
          ),
        ],
      ),
    ],
  },
  {
    id: 'smollm',
    label: 'SmolLM',
    lineSummary: 'SmolLM 2 contributes one compact instruct family with an exact shared vocabulary across the listed sizes.',
    lineCaption: 'SmolLM currently contributes one public family here.',
    families: [
      family(
        'smollm2',
        'SmolLM 2',
        'exact',
        'Exact shared vocabulary',
        'The listed SmolLM 2 instruct checkpoints resolve to the same public tokenizer.json, so token IDs stay aligned from the 135M model up through the 1.7B release.',
        'All listed SmolLM 2 configurations point to the same tokenizer.json.',
        [
          model(
            'smollm2-135m-instruct',
            'SmolLM2-135M-Instruct',
            'HuggingFaceTB/SmolLM2-135M-Instruct',
            '135M',
            'SmolLM 2 instruct',
            'The smallest public SmolLM 2 instruct checkpoint, useful for seeing the exact shared SmolLM 2 vocabulary at tiny scale.',
            'Public SmolLM 2 tokenizer files for the 135M instruct release.',
          ),
          model(
            'smollm2-360m-instruct',
            'SmolLM2-360M-Instruct',
            'HuggingFaceTB/SmolLM2-360M-Instruct',
            '360M',
            'SmolLM 2 instruct',
            'Mid-sized SmolLM 2 instruct checkpoint that keeps the same tokenizer surface as the smaller and larger listed SmolLM 2 models.',
            'Public SmolLM 2 tokenizer files for the 360M instruct release.',
          ),
          model(
            'smollm2-1.7b-instruct',
            'SmolLM2-1.7B-Instruct',
            'HuggingFaceTB/SmolLM2-1.7B-Instruct',
            '1.7B',
            'SmolLM 2 instruct',
            'Largest listed SmolLM 2 checkpoint, still aligned to the same tokenizer.json as the smaller SmolLM 2 variants.',
            'Public SmolLM 2 tokenizer files for the 1.7B instruct release.',
          ),
        ],
        {
          tokenizerSource: 'HuggingFaceTB/SmolLM2-135M-Instruct',
          tokenizerCacheKey: 'smollm2',
          tokenizerSourceLabel: 'shared tokenizer assets from HuggingFaceTB/SmolLM2-135M-Instruct',
        },
      ),
    ],
  },
  {
    id: 'falcon',
    label: 'Falcon',
    lineSummary: 'Falcon 3 contributes one instruct family with an exact shared tokenizer across the listed sizes.',
    lineCaption: 'Falcon currently contributes one public family here.',
    families: [
      family(
        'falcon3',
        'Falcon 3',
        'exact',
        'Exact shared vocabulary',
        'The listed Falcon 3 instruct checkpoints share the same public tokenizer.json, so vocabulary and token IDs stay consistent as you move across the 1B, 3B, 7B, and 10B sizes.',
        'All listed Falcon 3 configurations point to the same tokenizer.json.',
        [
          model(
            'falcon3-1b-instruct',
            'Falcon3-1B-Instruct',
            'tiiuae/Falcon3-1B-Instruct',
            '1B',
            'Falcon 3 instruct',
            'Smallest listed Falcon 3 instruct checkpoint with the exact shared Falcon 3 tokenizer surface.',
            'Public Falcon 3 tokenizer files for the 1B instruct release.',
          ),
          model(
            'falcon3-3b-instruct',
            'Falcon3-3B-Instruct',
            'tiiuae/Falcon3-3B-Instruct',
            '3B',
            'Falcon 3 instruct',
            'Mid-sized Falcon 3 instruct checkpoint that keeps the same tokenizer surface as the other listed Falcon 3 sizes.',
            'Public Falcon 3 tokenizer files for the 3B instruct release.',
          ),
          model(
            'falcon3-7b-instruct',
            'Falcon3-7B-Instruct',
            'tiiuae/Falcon3-7B-Instruct',
            '7B',
            'Falcon 3 instruct',
            'Larger Falcon 3 instruct checkpoint that still reuses the exact shared Falcon 3 tokenizer bundle.',
            'Public Falcon 3 tokenizer files for the 7B instruct release.',
          ),
          model(
            'falcon3-10b-instruct',
            'Falcon3-10B-Instruct',
            'tiiuae/Falcon3-10B-Instruct',
            '10B',
            'Falcon 3 instruct',
            'Largest public Falcon 3 instruct checkpoint in the family ladder, still aligned to the same tokenizer surface.',
            'Public Falcon 3 tokenizer files for the 10B instruct release.',
          ),
        ],
        {
          tokenizerSource: 'tiiuae/Falcon3-1B-Instruct',
          tokenizerCacheKey: 'falcon3',
          tokenizerSourceLabel: 'shared tokenizer assets from tiiuae/Falcon3-1B-Instruct',
        },
      ),
    ],
  },
];

export const UNSUPPORTED_BROWSER_LINES = [
  {
    label: 'GLM 4',
    reason: 'Public repos rely on a custom ChatGLM tokenizer class.',
  },
  {
    label: 'InternLM 3',
    reason: 'Public repos rely on a custom InternLM tokenizer class.',
  },
  {
    label: 'Baichuan 2',
    reason: 'Public repos rely on a custom Baichuan tokenizer class.',
  },
];
